spring:
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite:memory:lunchies?cache=shared
    username: lunchies
    password: 123456
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
