server:
  port: 9090
  ssl:
    key-store: classpath:lunchies.pfx
    key-store-password: 123456
    key-store-type: pkcs12
    key-alias: lunchies
    key-password: 123456

spring:
  security:
    oauth2:
      client:
        registration:
          lunchies-client-oidc:
            provider: spring
            client-id: lunchies-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "https://127.0.0.1:9090/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: lunchies-client-oidc
          lunchies-client-authorization:
            provider: spring
            client-id: lunchies-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "https://127.0.0.1:9090/login/oauth2/code/{registrationId}"
            scope: lunchies.user
            client-name: lunchies-client-authorization
        provider:
          spring:
            issuer-uri: http://lunchies-auth-server:9000
