name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build User Service
      working-directory: ./user
      run: mvn package --file pom.xml
      
    - name: Build Product Service
      working-directory: ./product
      run: mvn package --file pom.xml

    - name: Build Order Service
      working-directory: ./order
      run: mvn package --file pom.xml

    - name: Build GUI Service
      working-directory: ./gui
      run: mvn package --file pom.xml
